# Generated by Django 5.2.1 on 2025-06-12 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_migrate_old_profiles_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profils"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_city",
            field=models.CharField(
                blank=True,
                help_text="Ville préférée de l'utilisateur (facultatif)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="Utilisateur associé à ce profil",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
