# Generated by Django 5.2.1 on 2025-06-12 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_migrate_old_lettings_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Adresse", "verbose_name_plural": "Adresses"},
        ),
        migrations.AlterModelOptions(
            name="letting",
            options={"verbose_name": "Annonce", "verbose_name_plural": "Annonces"},
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(help_text="Ville", max_length=64),
        ),
        migrations.AlterField(
            model_name="address",
            name="country_iso_code",
            field=models.CharField(
                help_text="Code ISO du pays (ex : FRA, USA)",
                max_length=3,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.PositiveIntegerField(
                help_text="Numéro de la voie (ex : 221)",
                validators=[django.core.validators.MaxValueValidator(9999)],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                help_text="État (2 lettres)",
                max_length=2,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(help_text="Nom de la rue", max_length=64),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.PositiveIntegerField(
                help_text="Code postal",
                validators=[django.core.validators.MaxValueValidator(99999)],
            ),
        ),
        migrations.AlterField(
            model_name="letting",
            name="address",
            field=models.OneToOneField(
                help_text="Adresse associée à la location",
                on_delete=django.db.models.deletion.CASCADE,
                to="lettings.address",
            ),
        ),
        migrations.AlterField(
            model_name="letting",
            name="title",
            field=models.CharField(
                help_text="Titre de l'annonce (ex : Appartement cosy à Paris)",
                max_length=256,
            ),
        ),
    ]
